name: Github Workflow Stats
description: Export Github Workflow stats into Postgres
author: Fedor Dikarev
branding:
  icon: activity
  color: yellow

# Define your inputs here.
inputs:
  db_uri:
    description: Postgres DB URI
    required: true

runs:
  using: docker
  image: "docker://yatheo/gh-workflow-stats-action:latest"
  env:
    DB_URI: ${{ inputs.db_uri }}
