name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

env:
  IMAGE_NAME: gh-workflow-stats-action

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images:
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            # branch event
            type=ref,enable=true,priority=600,prefix=,suffix=,event=branch
            # pull request event
            type=ref,enable=true,priority=600,prefix=pr-,suffix=,event=pr
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
